spring.application.name=brickapi
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5433/brickdb
spring.datasource.username=postgres
spring.datasource.password=heslo
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.basic.enabled=false
management.security.enabled=false

lego.url.bricklink-set=https://www.bricklink.com/v2/catalog/catalogitem.page?S=
lego.url.lego-retired-item=https://www.lego.com/cs-cz/categories/last-chance-to-buy?page=
lego.url.brickeconomy-item=https://www.brickeconomy.com/set/

